### PR TITLE
SYN

### PR DESCRIPTION
**Pull request by justin-bacon**
- add support for yubrowser
- add simplified chinese

### CODE REVIEW

**Comment by JayT5** [comment]
Thanks! Can I ask why you removed the Gradle script?

**Comment by justin-bacon** [comment]
I imported it to Android Studio,and then it changed like this.I don't know when the Gradle script disappeared

**Comment by JayT5** [comment]
Do you mind adding it back, then I can (finally) merge this :+1:

**Comment by justin-bacon** [comment]
I have added them.If you have any other requests,please tell me.

**Comment by JayT5** [comment]
You've added/changed a few other files now, make sure it's just the `strings.xml` and `PieSettings.java` files that have been modified.

**Comment by justin-bacon** [comment]
yes,just these two.when you merged,I will close pull request.

**Comment by JayT5** [comment]
Okay, I'll merge manually

**Pull request closed without merging**
